### ISSUE TITLE
error occurred with non-exist vpc-name on ssh subcommand

### ISSUE THREAD

**Issue by hirakiuc** [hirakiuc/ec2s#16]
```
$ ec2s ssh --vpc-name non-exist-vpc-name
No such vpc found: non-exist-vpc-name: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x40 pc=0xbd375]

goroutine 1 [running]:
_/Users/hirakiuc/Desktop/github/ec2s/common.(*InstanceFilter).vpcIdForFilter(0xc20801e720, 0xc20802ae58, 0x0, 0x0)
        /Users/hirakiuc/Desktop/github/ec2s/common/filter.go:28 +0xa5
_/Users/hirakiuc/Desktop/github/ec2s/common.(*InstanceFilter).VpcFilter(0xc20801e720, 0x7ca6a0, 0x0, 0x0)
        /Users/hirakiuc/Desktop/github/ec2s/common/filter.go:36 +0x40
_/Users/hirakiuc/Desktop/github/ec2s/common.(*InstanceFilter).InstancesFilter(0xc20801e720, 0x0, 0x0, 0x0)
        /Users/hirakiuc/Desktop/github/ec2s/common/filter.go:57 +0x7d
_/Users/hirakiuc/Desktop/github/ec2s/command/list.ShowEc2Instances(0x8c8070, 0xc2080782a0, 0x8c84c8, 0xc20801e700, 0xc20800a6c0)
        /Users/hirakiuc/Desktop/github/ec2s/command/list/logic.go:46 +0x207
_/Users/hirakiuc/Desktop/github/ec2s/chooser.ChooseEc2Instances(0x8c84c8, 0xc20801e700, 0x0, 0x0, 0x0, 0x1)
        /Users/hirakiuc/Desktop/github/ec2s/chooser/ec2_chooser.go:38 +0x134
_/Users/hirakiuc/Desktop/github/ec2s/command/ssh.(*Command).Run(0xc20801e700, 0xc20800a020, 0x2, 0x2, 0xc208032718)
        /Users/hirakiuc/Desktop/github/ec2s/command/ssh/command.go:36 +0x82
github.com/mitchellh/cli.(*CLI).Run(0xc20804c0b0, 0xc20803b650, 0x0, 0x0)
        /Users/hirakiuc/Desktop/github/ec2s/.bundle/src/github.com/mitchellh/cli/cli.go:112 +0x5be
main.main()
        /Users/hirakiuc/Desktop/github/ec2s/main.go:35 +0x268

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/Cellar/go/1.4.2/libexec/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 10 [runnable]:
net/http.(*persistConn).readLoop(0xc20804c160)
        /usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
        /usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:660 +0xc9f

goroutine 11 [select]:
net/http.(*persistConn).writeLoop(0xc20804c160)
        /usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /usr/local/Cellar/go/1.4.2/libexec/src/net/http/transport.go:661 +0xcbc

```

**Comment by hirakiuc** [comment]
pull request #17 merged.
